=== benothman/Register-Portlet/src/main/webapp/WEB-INF/profile-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : profile-config.xsd
    Created on : November 11, 2010, 2:31 PM
    Author     : Nabil Benothman
    Description: Define the structure of the profile-config.xml
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element  name="properties" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property"  minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="short-name" type="xs:string"/>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element ref="access-mode"/>
                            <xs:element ref="usage"/>
                            <xs:element ref="display-name"/>
                            <xs:element ref="description"/>
                            <xs:element ref="mapping"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="access-mode">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="read-only"/>
                <xs:enumeration value="write-only"/>
                <xs:enumeration value="read-write"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="usage">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="required"/>
                <xs:enumeration value="optionel"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="display-name">
        <xs:complexType mixed="true">
            <xs:attribute name="lang" type="xs:string" default="EN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="description">
        <xs:complexType mixed="true">
            <xs:attribute name="lang" type="xs:string" default="EN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="database">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="value" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== benothman/Register-Portlet/src/main/webapp/WEB-INF/profile-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : profile-config.xml
    Created on : November 11, 2010, 2:31 PM
    Author     : Nabil Benothman
    Description: Define the user properties
-->

<properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="profile-config.xsd">

    <property>
        <name>toto</name>
        <short-name>t</short-name>
        <type>string</type>
        <access-mode>read-write</access-mode>
        <usage>optionel</usage>
        <display-name lang="EN">asasdasd</display-name>
        <description lang="EN">asdasd</description>
        <mapping>
            <database>
                <type>adasd</type>
                <value>asdas</value>
            </database>
        </mapping>
    </property>
    <property>
        <name>toto</name>
        <short-name>t</short-name>
        <type>string</type>
        <access-mode>read-write</access-mode>
        <usage>optionel</usage>
        <display-name lang="EN">asasdasd</display-name>
        <description lang="EN">asdasd</description>
        <mapping>
            <database>
                <type>adasd</type>
                <value>asdas</value>
            </database>
        </mapping>
    </property>

</properties>
