=== benothman/Register-Portlet/src/main/webapp/WEB-INF/ui-components-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : ui-components-config.xsd
    Created on : November 11, 2010, 2:31 PM
    Author     : Nabil Benothman
    Description: Define the structure of the ui-components-config.xml
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element  name="ui-components" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ui-component"  minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="property-ref" type="xs:string"/>
                            <xs:element name="required" type="xs:boolean"/>
                            <xs:element ref="values" minOccurs="0"/>
                        </xs:all>
                        <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="values">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="value" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:attribute name="key" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== benothman/Register-Portlet/src/main/webapp/WEB-INF/ui-components-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ui-components-config.xml
    Created on : November 11, 2010, 2:31 PM
    Author     : Nabil Benothman
    Description: file define the UI components that will be used to build JSF UI
-->

<ui-components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ui-components-config.xsd">
    
    <ui-component name="firstname">
        <property-ref>portal.user.firstname</property-ref>
        <required>true</required>
    </ui-component>

    <ui-component name="lastname">
        <property-ref>portal.user.lastname</property-ref>
        <required>true</required>
    </ui-component>

    <ui-component name="email">
        <property-ref>portal.user.email</property-ref>
        <required>true</required>
    </ui-component>

    <ui-component name="username">
        <property-ref>portal.user.username</property-ref>
        <required>true</required>
    </ui-component>

    <ui-component name="password">
        <property-ref>portal.user.password</property-ref>
        <required>true</required>
    </ui-component>

    <ui-component name="confirmPassword">
        <property-ref>portal.user.confirmPassword</property-ref>
        <required>true</required>
    </ui-component>

    <ui-component name="captcha">
        <property-ref>portal.user.captcha.answer</property-ref>
        <required>true</required>
    </ui-component>
    
    <ui-component name="gender">
        <property-ref>portal.user.gender</property-ref>
        <required>false</required>
        <values>
            <value key="male">Male</value>
            <value key="female">Female</value>
        </values>
    </ui-component>
    
    <ui-component name="title">
        <property-ref>portal.user.title</property-ref>
        <required>false</required>
        <values>
            <value key="Mr">Mr</value>
            <value key="Mrs">Mrs</value>
            <value key="Ms">Ms</value>
        </values>
    </ui-component>
    <ui-component name="birthday">
        <property-ref>portal.user.birthday</property-ref>
        <required>false</required>
    </ui-component>

    <ui-component name="address.line1">
        <property-ref>portal.user.address.line1</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="address.line2">
        <property-ref>portal.user.address.line2</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="address.zipCode">
        <property-ref>portal.user.address.zipCode</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="address.city">
        <property-ref>portal.user.address.city</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="address.state">
        <property-ref>portal.user.address.state</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="address.country">
        <property-ref>portal.user.address.country</property-ref>
        <required>false</required>
    </ui-component>
    
    <ui-component name="phone">
        <property-ref>portal.user.phone</property-ref>
        <required>false</required>
    </ui-component>

    <ui-component name="skype">
        <property-ref>portal.user.skype</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="linkedIn">
        <property-ref>portal.user.linkedIn</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="twitter">
        <property-ref>portal.user.twitter</property-ref>
        <required>false</required>
    </ui-component>
    <ui-component name="msn">
        <property-ref>portal.user.msn</property-ref>
        <required>false</required>
    </ui-component>
</ui-components>
